In [1]:
#import dependencies
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [2]:
#read in abortion data by state
#data ends in 2017
abortion_facts = pd.read_csv('GuttmacherDataCenter.csv')

In [3]:
#abortion_facts.columns

In [4]:
#rename column "summary" to "shootings"
abortion_facts = abortion_facts.rename(columns={"U.S. State":"State"})

In [5]:
#abortion_trial = abortion_facts[['State','% of all U.S. abortions, by state of occurrence, 2017']]
#abortion_trial

In [6]:
# Set option to display all rows
pd.set_option('display.max_rows', None)

In [7]:
#read in abortion data by state
#data ends in 2017
abortion_state = pd.read_csv('Guttmacher_Webscrape.csv')

In [8]:
#abortion_state.head()

In [10]:
#do an inner join to merge data frames on year and state, so that the law total is added only per state and year with a mass shooting
df_abortion = pd.merge(abortion_facts, abortion_state, how="inner",on=["State"])
#df_abortion["No. of women who likely need public support for contraceptive s"]
#df_abortion.columns

In [23]:
df_abortion.columns=df_abortion.columns.str.replace(","," ")
df_abortion.head()

,State,% change in abortion rate (the no. of abortions per 1 000 women aged 15-44) by state of occurrence 2014-2017,% change in the no. of abortion clinics 2014-2017 [2],% change in the no. of abortion providers 2014-2017 [2],% change in women who likely need public support for contraceptive services and supplies 2016,% of all U.S. abortions by state of occurrence 2017,% of women aged 15-44 covered by Medicaid 2017,% of women aged 15-44 covered by private insurance 2017,% of women aged 15-44 who are uninsured 2017,% uninsured women aged 20-44 and <138% of the federal poverty level who likely need public support for contraceptive services and supplies 2016,...,% WORA: 25-29 Years,% WORA: 30-39 Years,% WORA: 40-49 Years,Avg. Distance (mi): 6 Weeks,Avg. Distance (mi): 12 Weeks,Avg. Distance (mi): 14 Weeks,Avg. Distance (mi): 20 Weeks,Avg. Distance (mi): 22 Weeks,Avg. Distance (mi): 24 Weeks,Avg. Distance (mi): 24+ Weeks
0,Alabama,-23,0,-22,10,0.7,18,63,14,28,...,15.0,29.0,28.0,NaN,115.0,118.0,137.0,179.0,474.0,507.0
1,Alaska,-14,33,-25,6,0.1,24,49,15,31,...,18.0,33.0,26.0,NaN,9.0,11.0,NaN,NaN,NaN,NaN
2,Arizona,-6,-11,-8,8,1.4,24,60,13,21,...,15.0,28.0,27.0,NaN,NaN,NaN,11.0,NaN,22.0,25.0
3,Arkansas,-30,0,0,13,0.4,28,58,11,20,...,15.0,29.0,28.0,NaN,NaN,NaN,160.0,328.0,NaN,360.0
4,California,-16,6,-18,2,15.4,27,62,9,18,...,16.0,30.0,27.0,NaN,4.0,8.0,9.0,12.0,NaN,14.0

In [24]:
df_abortion.columns = [x.replace('No. of women who likely need public support for contraceptive services and supplies','services needed:') for x in df_abortion.columns]

In [25]:
#df_abortion.columns

In [26]:
#establish the connection to postgresql
protocol = 'postgresql'
username = 'postgres'
password = 'admin'
host = 'localhost'
port = 5432
database_name = 'abortion_db_sql'
rds_connection_string = f'{protocol}://{username}:{password}@{host}:{port}/{database_name}'
engine = create_engine(rds_connection_string)

In [28]:
#create table in sql
#check table exists
engine.table_names()

C:\Users\US11338\AppData\Local\Temp/ipykernel_668/1858051120.py:3: SADeprecationWarning: The Engine.table_names() method is deprecated and will be removed in a future release.  Please refer to Inspector.get_table_names(). (deprecated since: 1.4)
  engine.table_names()

['df_abortion']

In [29]:
#upload dataframes into sql
df_abortion.to_sql(name='df_abortion_sql', con=engine, if_exists='append', index=True)

In [30]:
pd.read_sql_query("select * from df_abortion_sql", con=engine)

,index,State,% change in abortion rate (the no. of abortions per 1 000 women,% change in the no. of abortion clinics 2014-2017 [2],% change in the no. of abortion providers 2014-2017 [2],% change in women who likely need public support for contracept,% of all U.S. abortions by state of occurrence 2017,% of women aged 15-44 covered by Medicaid 2017,% of women aged 15-44 covered by private insurance 2017,% of women aged 15-44 who are uninsured 2017,...,% WORA: 25-29 Years,% WORA: 30-39 Years,% WORA: 40-49 Years,Avg. Distance (mi): 6 Weeks,Avg. Distance (mi): 12 Weeks,Avg. Distance (mi): 14 Weeks,Avg. Distance (mi): 20 Weeks,Avg. Distance (mi): 22 Weeks,Avg. Distance (mi): 24 Weeks,Avg. Distance (mi): 24+ Weeks
0,0,Alabama,-23,0,-22,10,0.7,18,63,14,...,15.0,29.0,28.0,NaN,115.0,118.0,137.0,179.0,474.0,507.0
1,1,Alaska,-14,33,-25,6,0.1,24,49,15,...,18.0,33.0,26.0,NaN,9.0,11.0,NaN,NaN,NaN,NaN
2,2,Arizona,-6,-11,-8,8,1.4,24,60,13,...,15.0,28.0,27.0,NaN,NaN,NaN,11.0,NaN,22.0,25.0
3,3,Arkansas,-30,0,0,13,0.4,28,58,11,...,15.0,29.0,28.0,NaN,NaN,NaN,160.0,328.0,NaN,360.0
4,4,California,-16,6,-18,2,15.4,27,62,9,...,16.0,30.0,27.0,NaN,4.0,8.0,9.0,12.0,NaN,14.0
5,5,Colorado,-10,-14,-11,9,1.4,20,66,10,...,16.0,32.0,26.0,NaN,9.0,NaN,11.0,20.0,22.0,851.0
6,6,Connecticut,-8,4,-8,3,1.4,23,68,7,...,13.0,28.0,29.0,NaN,6.0,NaN,15.0,NaN,17.0,64.0
7,7,Delaware,-37,33,0,7,0.2,19,70,7,...,15.0,30.0,27.0,NaN,NaN,NaN,2.0,NaN,NaN,3.0
8,8,Florida,-10,-8,-1,19,8.2,17,62,18,...,15.0,30.0,29.0,NaN,8.0,10.0,12.0,16.0,22.0,910.0
9,9,Georgia,8,-12,-7,14,4.2,13,64,19,...,14.0,29.0,28.0,NaN,17.0,24.0,29.0,38.0,450.0,558.0
10,10,Hawaii,-14,0,-3,-3,0.4,18,63,5,...,15.0,31.0,29.0,13.0,NaN,NaN,14.0,NaN,19.0,0.0
11,11,Idaho,-6,0,0,3,0.1,15,66,16,...,15.0,29.0,26.0,NaN,21.0,NaN,36.0,286.0,NaN,428.0
12,12,Illinois,2,4,0,2,4.9,22,68,9,...,15.0,29.0,28.0,NaN,7.0,NaN,10.0,NaN,26.0,266.0
13,13,Indiana,-6,-33,-18,8,0.9,19,68,11,...,14.0,29.0,27.0,NaN,23.0,43.0,155.0,NaN,174.0,235.0
14,14,Iowa,-15,-33,-31,7,0.4,20,73,5,...,15.0,29.0,26.0,NaN,33.0,NaN,47.0,170.0,229.0,252.0
15,15,Kansas,-5,0,0,5,0.8,12,71,11,...,15.0,27.0,27.0,NaN,30.0,NaN,NaN,31.0,330.0,355.0
16,16,Kentucky,-9,-50,0,12,0.4,30,60,7,...,14.0,28.0,29.0,99.0,NaN,118.0,158.0,268.0,NaN,274.0
17,17,Louisiana,-2,-20,-20,11,1.2,31,56,10,...,16.0,31.0,26.0,NaN,NaN,37.0,71.0,525.0,638.0,673.0
18,18,Maine,-7,300,133,-4,0.2,19,68,11,...,13.0,29.0,31.0,NaN,12.0,25.0,32.0,NaN,147.0,321.0
19,19,Maryland,7,0,7,11,3.5,19,70,8,...,14.0,31.0,29.0,NaN,6.0,NaN,7.0,NaN,15.0,29.0
20,20,Massachusetts,-12,36,9,2,2.2,25,70,3,...,15.0,29.0,26.0,NaN,8.0,NaN,9.0,13.0,23.0,180.0
21,21,Michigan,-8,5,3,4,3.1,26,67,6,...,15.0,29.0,26.0,NaN,11.0,NaN,13.0,NaN,19.0,26.0
22,22,Minnesota,9,17,0,5,1.2,20,73,6,...,15.0,30.0,27.0,NaN,16.0,17.0,18.0,NaN,21.0,25.0
23,23,Mississippi,13,0,50,9,0.3,20,58,17,...,15.0,29.0,28.0,NaN,NaN,80.0,90.0,378.0,NaN,499.0
24,24,Missouri,-8,200,100,4,0.5,14,70,13,...,15.0,30.0,27.0,NaN,NaN,NaN,NaN,44.0,NaN,155.0
25,25,Montana,-9,0,0,11,0.2,22,63,11,...,14.0,29.0,28.0,NaN,22.0,49.0,77.0,232.0,569.0,667.0
26,26,Nebraska,-13,0,40,11,0.2,11,73,12,...,16.0,29.0,25.0,NaN,NaN,NaN,10.0,51.0,377.0,397.0
27,27,Nevada,-15,-13,-15,12,1.1,19,63,15,...,16.0,29.0,29.0,NaN,7.0,8.0,9.0,NaN,11.0,238.0
28,28,New Hampshire,-12,0,0,2,0.3,14,76,7,...,13.0,30.0,28.0,NaN,12.0,NaN,17.0,58.0,59.0,215.0
29,29,New Jersey,9,0,-4,4,5.6,17,70,11,...,14.0,29.0,29.0,NaN,5.0,6.0,8.0,NaN,13.0,16.0
30,30,New Mexico,0,-33,-36,4,0.5,38,46,12,...,15.0,30.0,26.0,NaN,24.0,NaN,37.0,NaN,64.0,423.0
31,31,New York,-11,19,16,-1,12.2,27,65,7,...,16.0,31.0,27.0,NaN,3.0,4.0,5.0,8.0,9.0,10.0
32,32,North Carolina,-3,-13,-30,16,3.4,17,63,15,...,15.0,28.0,29.0,NaN,NaN,18.0,26.0,27.0,NaN,335.0
33,45,Virginia,-18,-11,-6,14,2.0,11,69,12,...,14.0,30.0,28.0,NaN,NaN,NaN,14.0,27.0,NaN,113.0
34,33,North Dakota,-9,0,0,11,0.1,10,74,10,...,14.0,29.0,25.0,NaN,NaN,NaN,165.0,326.0,399.0,402.0
35,34,Ohio,-9,-25,-18,6,2.4,25,65,7,...,15.0,29.0,28.0,19.0,NaN,120.0,149.0,NaN,157.0,195.0
36,35,Oklahoma,-11,33,20,15,0.6,14,61,20,...,15.0,29.0,27.0,NaN,NaN,NaN,180.0,181.0,500.0,512.0
37,36,Oregon,-1,7,7,8,1.1,25,65,9,...,15.0,30.0,29.0,NaN,7.0,11.0,29.0,35.0,NaN,36.0
38,37,Pennsylvania,-1,-10,2,0,3.6,21,70,7,...,15.0,30.0,27.0,NaN,11.0,14.0,20.0,28.0,29.0,84.0
39,38,Rhode Island,-2,-33,-40,0,0.4,26,66,6,...,15.0,28.0,27.0,NaN,7.0,NaN,8.0,18.0,46.0,149.0
40,46,Washington,-12,21,2,8,2.1,21,66,8,...,16.0,32.0,27.0,NaN,6.0,10.0,14.0,20.0,NaN,21.0
41,39,South Carolina,-17,33,43,14,0.6,18,62,16,...,15.0,29.0,28.0,23.0,NaN,74.0,102.0,107.0,427.0,492.0
42,40,South Dakota,-10,0,0,6,0.1,13,72,12,...,13.0,29.0,26.0,NaN,190.0,NaN,191.0,220.0,277.0,290.0
43,41,Tennessee,-14,14,9,14,1.4,22,63,11,...,16.0,29.0,28.0,NaN,26.0,27.0,29.0,236.0,NaN,320.0
44,42,Texas,-3,-25,-20,15,6.4,12,61,24,...,15.0,30.0,27.0,NaN,NaN,NaN,250.0,547.0,705.0,786.0
45,43,Utah,-4,50,100,8,0.3,9,78,11,...,15.0,27.0,25.0,NaN,NaN,NaN,30.0,33.0,416.0,652.0
46,44,Vermont,-5,0,11,0,0.2,32,62,5,...,12.0,30.0,26.0,NaN,16.0,38.0,40.0,97.0,201.0,285.0
47,47,West Virginia,-26,-50,-40,6,0.2,34,56,8,...,14.0,27.0,31.0,NaN,NaN,64.0,65.0,126.0,167.0,283.0
48,48,Wisconsin,6,-25,-14,6,0.7,18,74,7,...,14.0,30.0,27.0,NaN,34.0,NaN,37.0,77.0,125.0,242.0
49,49,Wyoming,22,0,-33,9,0.0,13,66,17,...,11.0,35.0,25.0,NaN,132.0,NaN,169.0,181.0,331.0,829.0